"use client";

/* eslint-disable @next/next/no-img-element */
import { CSSProperties, FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import BuilderSection from "@/components/BuilderSection";
import type { Announcement, ClassSchedule, Course, Faq, PageSection, PublicContent } from "@/lib/content";
import { direction, Lang, publicCopy } from "@/lib/public-copy";

type LocalField="title"|"description"|"category"|"duration"|"level"|"format"|"outcomes";
const suffix:Record<Lang,"Fa"|"En"|"Ps">={fa:"Fa",en:"En",ps:"Ps"};
const localCourse=(course:Course,field:LocalField,lang:Lang)=>String(course[`${field}${suffix[lang]}` as keyof Course]??"");
const localAnnouncement=(item:Announcement,field:"title"|"excerpt",lang:Lang)=>String(item[`${field}${suffix[lang]}` as keyof Announcement]??"");
const localSchedule=(item:ClassSchedule,field:"courseTitle"|"days"|"seats",lang:Lang)=>String(item[`${field}${suffix[lang]}` as keyof ClassSchedule]??"");
const localFaq=(item:Faq,field:"question"|"answer",lang:Lang)=>String(item[`${field}${suffix[lang]}` as keyof Faq]??"");
const localSection=(item:PageSection,field:"eyebrow"|"heading"|"body"|"imageAlt"|"ctaLabel"|"navLabel",lang:Lang)=>String(item[`${field}${suffix[lang]}` as keyof PageSection]??"");

function Icon({name,size=22}:{name:string;size?:number}){
  const p={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};
  const map:Record<string,ReactNode>={
    target:<><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="m15 9 5-5M16 4h4v4"/></>,
    message:<><path d="M4 5h16v11H8l-4 4V5Z"/><path d="M8 9h8M8 12h5"/></>,
    computer:<><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/></>,
    science:<><path d="M9 3h6M10 3v6l-5 9a2 2 0 0 0 1.7 3h10.6a2 2 0 0 0 1.7-3l-5-9V3"/><path d="M8 15h8"/></>,
    chart:<><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></>,
    code:<><path d="m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14"/></>,
    phone:<path d="M7 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-3l-4-1-2 2c-4-1.6-7.4-5-9-9l2-2-1-4Z"/>,
    pin:<><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>,
    arrow:<path d="M5 12h14M13 6l6 6-6 6"/>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,
    users:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.8M16 3.2a4 4 0 0 1 0 7.6"/></>,
    exam:<><path d="M6 3h12v18H6z"/><path d="M9 8h6M9 12h6M9 16h3"/></>,shield:<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/>,
    check:<path d="m5 12 4 4L19 6"/>,book:<><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Z"/><path d="M4 18.5A2.5 2.5 0 0 1 6.5 16H20"/></>,
    close:<><path d="m6 6 12 12M18 6 6 18"/></>,compare:<><path d="M4 7h16M7 4 4 7l3 3M20 17H4M17 14l3 3-3 3"/></>,
    verified:<><path d="m12 2 2.5 2 3.2-.2.8 3.1 2.6 1.8-1.2 3 1.2 3-2.6 1.8-.8 3.1-3.2-.2-2.5 2-2.5-2-3.2.2-.8-3.1-2.6-1.8 1.2-3-1.2-3 2.6-1.8.8-3.1 3.2.2L12 2Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,
    route:<><circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h3a3 3 0 0 0 3-3v-6a3 3 0 0 1 3-3"/></>,
    support:<><path d="M4 13a8 8 0 0 1 16 0"/><path d="M4 13v5h3v-5H4ZM17 13v5h3v-5h-3ZM17 20c-1 1-2.5 1.5-5 1.5"/></>,
  };
  return <svg {...p}>{map[name]??map.book}</svg>;
}

function Brand({light=false,large=false}:{light?:boolean;large?:boolean}){
  return <div className="brand" dir="ltr"><img className={large?"brand-logo brand-logo-large":"brand-logo"} src="/images/raufi-logo.webp" alt="Raufi Learning Center logo"/><span className="brand-copy"><strong className={light?"text-white":"text-[#092f4f]"}>RAUFI</strong><small className={light?"text-blue-100":"text-[#60758a]"}>LEARNING CENTER</small></span></div>;
}

function CourseCard({course,lang,onOpen,onCompare,compared}:{course:Course;lang:Lang;onOpen:()=>void;onCompare:()=>void;compared:boolean}){
  const t=publicCopy[lang],style={"--course-accent":course.accent||"#1261a0"} as CSSProperties;
  return <article className="program-card" style={style}>
    <div className="program-card-top"><span className="program-icon"><Icon name={course.icon}/></span>{course.featured?<span className="featured-chip">{t.featured}</span>:null}</div>
    <span className="program-category">{localCourse(course,"category",lang)}</span><h3>{localCourse(course,"title",lang)}</h3><p>{localCourse(course,"description",lang)}</p>
    <div className="program-meta"><span><Icon name="clock" size={16}/>{localCourse(course,"duration",lang)||"—"}</span><span><Icon name="users" size={16}/>{localCourse(course,"level",lang)||"—"}</span></div>
    <div className="program-actions"><button type="button" className="program-link" onClick={onOpen}>{t.details}<Icon name="arrow" size={17}/></button><button type="button" className={compared?"compare-button active":"compare-button"} aria-pressed={compared} onClick={onCompare}><Icon name={compared?"check":"compare"} size={16}/>{compared?t.selected:t.compare}</button></div>
  </article>;
}

export default function PublicSite({initialContent}:{initialContent:PublicContent}){
  const [lang,setLang]=useState<Lang>("fa");
  const [menu,setMenu]=useState(false),[languageMenu,setLanguageMenu]=useState(false);
  const [query,setQuery]=useState(""),[category,setCategory]=useState("all");
  const [activeCourse,setActiveCourse]=useState<Course|null>(null),[compareOpen,setCompareOpen]=useState(false);
  const [compareIds,setCompareIds]=useState<string[]>([]),[finderGoal,setFinderGoal]=useState("");
  const [openFaq,setOpenFaq]=useState<string|null>(initialContent.faqs[0]?.id??null),[selectedInterest,setSelectedInterest]=useState("");
  const [formState,setFormState]=useState<"idle"|"sending"|"sent"|"error">("idle");
  const t=publicCopy[lang],dir=direction(lang);
  const setting=(name:string)=>initialContent.settings[`${name}${suffix[lang]}`]??initialContent.settings[`${name}En`]??"";
  const sections=useMemo(()=>[...initialContent.sections].sort((a,b)=>a.sortOrder-b.sortOrder),[initialContent.sections]);
  const sectionMap=useMemo(()=>new Map(sections.map(section=>[section.sectionKey,section])),[sections]);
  const sectionValue=(key:string,field:"eyebrow"|"heading"|"body"|"imageAlt"|"ctaLabel",fallback:string)=>{const section=sectionMap.get(key);return section?localSection(section,field,lang)||fallback:fallback;};
  const sectionStyle=(key:string)=>({order:sectionMap.get(key)?.sortOrder??999,display:sectionMap.has(key)?undefined:"none"} as CSSProperties);
  const standardKeys=new Set(["hero","facts","programmes","about","finder","advantages","journey","support","environment","schedule","news","faq","enrolment"]);
  const customSections=sections.filter(section=>!standardKeys.has(section.sectionKey));
  const navigation=useMemo(()=>[
    ...sections.filter(section=>section.showInNav).map(section=>({id:section.id,href:`#${section.sectionKey}`,label:localSection(section,"navLabel",lang)||section.name})),
    ...initialContent.pages.filter(page=>!page.isHome&&page.showInNav&&page.published).map(page=>({id:page.id,href:`/${page.slug}`,label:String(page[`navLabel${suffix[lang]}` as keyof typeof page]||page[`title${suffix[lang]}` as keyof typeof page])})),
  ],[sections,initialContent.pages,lang]);
  const categories=useMemo(()=>Array.from(new Map(initialContent.courses.map(course=>[course.categoryEn,localCourse(course,"category",lang)])).entries()),[initialContent.courses,lang]);
  const filteredCourses=useMemo(()=>initialContent.courses.filter(course=>{const matchesCategory=category==="all"||course.categoryEn===category;const haystack=`${course.titleFa} ${course.titleEn} ${course.titlePs} ${course.descriptionFa} ${course.descriptionEn} ${course.descriptionPs}`.toLowerCase();return matchesCategory&&haystack.includes(query.trim().toLowerCase());}),[initialContent.courses,category,query]);
  const comparedCourses=useMemo(()=>compareIds.map(id=>initialContent.courses.find(course=>course.id===id)).filter((course):course is Course=>Boolean(course)),[compareIds,initialContent.courses]);
  const recommendations=useMemo(()=>{const slugs:Record<string,string[]>={kankor:["kankor-preparation"],language:["english-language"],digital:["computer-icdl","quickbooks","web-design"],school:["science-subjects","kankor-preparation"]};return initialContent.courses.filter(course=>(slugs[finderGoal]??[]).includes(course.slug));},[finderGoal,initialContent.courses]);

  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setActiveCourse(null);setCompareOpen(false);setMenu(false);setLanguageMenu(false);}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
  useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=dir;},[lang,dir]);

  function toggleCompare(id:string){setCompareIds(current=>current.includes(id)?current.filter(item=>item!==id):current.length<3?[...current,id]:current);}
  function chooseProgramme(course:Course){setSelectedInterest(course.titleEn);setActiveCourse(null);setCompareOpen(false);window.setTimeout(()=>document.getElementById("enrolment")?.scrollIntoView({behavior:"smooth"}),20);}
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setFormState("sending");const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));data.sourceLanguage=lang;
    try{const response=await fetch("/api/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});if(!response.ok)throw new Error();form.reset();setSelectedInterest("");setFormState("sent");}catch{setFormState("error");}
  }

  return <main className="site-shell" dir={dir}>
    <div className="top-strip"><div className="container top-strip-inner"><span><span className="pulse-dot"/>{setting("registrationLabel")}</span><a href={`tel:${initialContent.settings.phone.replace(/\s/g,"")}`} dir="ltr"><Icon name="phone" size={15}/>{initialContent.settings.phone}</a></div></div>
    <header className="main-header"><div className="container header-inner"><a href="#top" aria-label="Raufi Learning Center home"><Brand/></a><nav className="desktop-nav main-nav" aria-label="Main navigation">{navigation.map(item=><a key={item.id} href={item.href}>{item.label}</a>)}</nav><div className="header-actions"><div className="language-picker"><button type="button" className="lang-switch" onClick={()=>setLanguageMenu(value=>!value)} aria-expanded={languageMenu}>{t.language}<span>⌄</span></button>{languageMenu?<div className="language-menu">{(["fa","ps","en"] as Lang[]).map(code=><button type="button" key={code} className={lang===code?"active":""} onClick={()=>{setLang(code);setLanguageMenu(false);setCategory("all");}}>{t.languages[code]}</button>)}</div>:null}</div><a className="primary-button desktop-nav" href="#enrolment">{t.consult}<Icon name="arrow" size={17}/></a><button type="button" className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Open menu"><span/><span/><span/></button></div></div>{menu?<nav className="mobile-nav" aria-label="Mobile navigation">{navigation.map(item=><a key={item.id} href={item.href} onClick={()=>setMenu(false)}>{item.label}</a>)}<a className="primary-button" href="#enrolment" onClick={()=>setMenu(false)}>{t.consult}</a></nav>:null}</header>

    <div className="managed-sections">

    <section id="top" className="hero-section" style={sectionStyle("hero")} ><div className="hero-orb hero-orb-one"/><div className="hero-orb hero-orb-two"/><div className="container hero-layout"><div className="hero-copy"><span className="section-kicker light"><span/>{sectionValue("hero","eyebrow",t.heroKicker)}</span><h1>{sectionValue("hero","heading",setting("heroTitle"))}</h1><p>{sectionValue("hero","body",setting("heroBody"))}</p><div className="hero-actions"><a className="gold-button" href={sectionMap.get("hero")?.ctaUrl||"#programmes"}>{sectionValue("hero","ctaLabel",t.viewProgrammes)}<Icon name="arrow" size={18}/></a><a className="ghost-button" href="#finder"><Icon name="target" size={18}/>{t.findProgramme}</a></div><div className="hero-mini-contact"><span><Icon name="phone" size={18}/></span><div><small>{t.callNow}</small><a dir="ltr" href={`tel:${initialContent.settings.phone.replace(/\s/g,"")}`}>{initialContent.settings.phone}</a></div></div></div><div className="hero-visual"><div className="hero-image-wrap"><img src={sectionMap.get("hero")?.imageUrl||"/images/raufi-hero.webp"} alt={sectionValue("hero","imageAlt",t.environmentTitle)}/><div className="hero-image-shade"/><span className="image-disclosure">{t.illustrative}</span><div className="hero-logo-seal"><img src="/images/raufi-logo.webp" alt={t.officialLogo}/></div><div className="hero-status-card"><span className="status-icon"><Icon name="calendar"/></span><div><strong>{t.open}</strong><p>{t.openSub}</p></div></div></div><div className="hero-dots"/></div></div></section>

    <section className="facts-strip" style={sectionStyle("facts")} ><div className="container facts-grid">{t.facts.map((label,index)=><article key={label}><strong>{index===0?initialContent.courses.length:t.factValues[index]}</strong><span>{index===0?t.factValues[0]:label}</span>{index===0?<small>{label}</small>:null}</article>)}</div></section>

    <section id="programmes" className="section programs-section" style={sectionStyle("programmes")} ><div className="container"><header className="section-heading center"><span className="section-kicker"><span/>{sectionValue("programmes","eyebrow",t.programmesKicker)}</span><h2>{sectionValue("programmes","heading",t.programmesTitle)}</h2><p>{sectionValue("programmes","body",t.programmesBody)}</p></header><div className="program-toolbar"><div className="category-tabs"><button type="button" className={category==="all"?"active":""} onClick={()=>setCategory("all")}>{t.all}</button>{categories.map(([key,label])=><button type="button" className={category===key?"active":""} key={key} onClick={()=>setCategory(key)}>{label}</button>)}</div><label className="search-box"><Icon name="search" size={19}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search}/></label></div><div className="program-grid">{filteredCourses.map(course=><CourseCard key={course.id} course={course} lang={lang} onOpen={()=>setActiveCourse(course)} onCompare={()=>toggleCompare(course.id)} compared={compareIds.includes(course.id)}/>)}</div>{!filteredCourses.length?<div className="empty-state"><Icon name="search" size={28}/><p>{t.noProgram}</p></div>:null}</div></section>

    <section id="about" className="section about-section" style={sectionStyle("about")} ><div className="container about-layout"><div className="about-media"><div className="about-image"><img src={sectionMap.get("about")?.imageUrl||"/images/raufi-classroom.webp"} alt={sectionValue("about","imageAlt",t.environmentTitle)}/><span className="image-disclosure">{t.illustrative}</span></div><div className="official-card"><span><Icon name="verified"/></span><div><strong>{t.officialInfo}</strong><p>{t.officialInfoBody}</p><a href={initialContent.settings.facebook} target="_blank" rel="noreferrer">Facebook <Icon name="arrow" size={15}/></a></div></div></div><div className="about-copy"><span className="section-kicker"><span/>{sectionValue("about","eyebrow",t.aboutKicker)}</span><h2>{sectionValue("about","heading",setting("aboutTitle"))}</h2><p>{sectionValue("about","body",setting("aboutBody"))}</p><div className="about-points">{t.aboutPoints.map(item=><article key={item.t}><span><Icon name={item.i}/></span><div><strong>{item.t}</strong><p>{item.d}</p></div></article>)}</div></div></div></section>

    <section id="finder" className="finder-section" style={sectionStyle("finder")} ><div className="container finder-card"><div className="finder-intro"><span className="section-kicker light"><span/>{sectionValue("finder","eyebrow",t.finderKicker)}</span><h2>{sectionValue("finder","heading",t.finderTitle)}</h2><p>{sectionValue("finder","body",t.finderBody)}</p><img src="/images/raufi-logo.webp" alt="" aria-hidden="true"/></div><div className="finder-options">{t.finderChoices.map(choice=><button type="button" key={choice.id} className={finderGoal===choice.id?"selected":""} onClick={()=>setFinderGoal(choice.id)}><span><Icon name={choice.id==="kankor"?"target":choice.id==="language"?"message":choice.id==="digital"?"computer":"science"}/></span><div><strong>{choice.label}</strong><small>{choice.desc}</small></div><Icon name="arrow" size={17}/></button>)}{finderGoal?<div className="finder-result"><small>{t.recommendation}</small><div>{recommendations.map(course=><button type="button" key={course.id} onClick={()=>setActiveCourse(course)}>{localCourse(course,"title",lang)}</button>)}</div><a href="#enrolment">{t.talkAdvisor}<Icon name="arrow" size={16}/></a></div>:null}</div></div></section>

    <section id="advantages" className="section why-section" style={sectionStyle("advantages")} ><div className="container why-layout"><div className="why-copy"><span className="section-kicker"><span/>{sectionValue("advantages","eyebrow",t.whyKicker)}</span><h2>{sectionValue("advantages","heading",t.whyTitle)}</h2><p>{sectionValue("advantages","body",t.whyBody)}</p><div className="why-image"><img src={sectionMap.get("advantages")?.imageUrl||"/images/raufi-classroom.webp"} alt={sectionValue("advantages","imageAlt",t.environmentTitle)}/><span className="image-disclosure">{t.illustrative}</span><div className="why-image-badge"><img src="/images/raufi-logo.webp" alt=""/><strong>{t.heroKicker}</strong></div></div></div><div className="benefit-grid">{t.benefits.map((item,index)=><article key={item.t}><div className="benefit-number">0{index+1}</div><span className="benefit-icon"><Icon name={item.i}/></span><h3>{item.t}</h3><p>{item.d}</p></article>)}</div></div></section>

    <section id="journey" className="section journey-section" style={sectionStyle("journey")} ><div className="container"><header className="section-heading center light-heading"><span className="section-kicker light"><span/>{sectionValue("journey","eyebrow",t.journeyKicker)}</span><h2>{sectionValue("journey","heading",t.journeyTitle)}</h2></header><div className="journey-grid">{t.steps.map((step,index)=><article key={step.n}><span className="journey-number">{step.n}</span><div className="journey-line"><i/><b>{index<3?"→":"✓"}</b></div><h3>{step.t}</h3><p>{step.d}</p></article>)}</div></div></section>

    <section className="section support-section" style={sectionStyle("support")} ><div className="container"><header className="section-heading split"><div><span className="section-kicker"><span/>{sectionValue("support","eyebrow",t.supportKicker)}</span><h2>{sectionValue("support","heading",t.supportTitle)}</h2></div><p>{sectionValue("support","body",t.supportBody)}</p></header><div className="support-grid">{t.supportItems.map((item,index)=><article key={item.t}><span className="support-index">0{index+1}</span><span className="support-icon"><Icon name={item.i}/></span><h3>{item.t}</h3><p>{item.d}</p></article>)}</div></div></section>

    <section className="section environment-section" style={sectionStyle("environment")} ><div className="container environment-layout"><div className="environment-gallery"><div className="gallery-main"><img src={sectionMap.get("environment")?.imageUrl||"/images/raufi-hero.webp"} alt={sectionValue("environment","imageAlt",t.environmentTitle)}/><span className="image-disclosure">{t.illustrative}</span></div><div className="gallery-side"><img src={sectionMap.get("environment")?.secondaryImageUrl||"/images/raufi-classroom.webp"} alt={sectionValue("environment","imageAlt",t.environmentTitle)}/></div><div className="gallery-logo"><img src="/images/raufi-logo.webp" alt={t.officialLogo}/></div></div><div className="environment-copy"><span className="section-kicker"><span/>{sectionValue("environment","eyebrow",t.environmentKicker)}</span><h2>{sectionValue("environment","heading",t.environmentTitle)}</h2><p>{sectionValue("environment","body",t.environmentBody)}</p><div className="address-card"><span><Icon name="pin"/></span><div><small>{t.visitCenter}</small><strong>{setting("address")}</strong></div></div></div></div></section>

    <section id="schedule" className="section schedule-section" style={sectionStyle("schedule")} ><div className="container"><header className="section-heading split"><div><span className="section-kicker"><span/>{sectionValue("schedule","eyebrow",t.scheduleKicker)}</span><h2>{sectionValue("schedule","heading",t.scheduleTitle)}</h2></div><p>{sectionValue("schedule","body",t.scheduleBody)}</p></header>{initialContent.schedules.length?<div className="schedule-table-wrap"><table className="schedule-table"><thead><tr><th>{t.programmesKicker}</th><th>{t.days}</th><th>{t.time}</th><th>{t.start}</th><th>{t.availability}</th></tr></thead><tbody>{initialContent.schedules.map(row=><tr key={row.id}><td><strong>{localSchedule(row,"courseTitle",lang)}</strong></td><td>{localSchedule(row,"days",lang)}</td><td dir="ltr">{row.time}</td><td>{row.startDate||"—"}</td><td><span className="availability-chip">{localSchedule(row,"seats",lang)||"—"}</span></td></tr>)}</tbody></table></div>:<div className="schedule-empty"><span><Icon name="calendar" size={28}/></span><div><strong>{t.noSchedule}</strong><p>{t.scheduleBody}</p></div><a className="primary-button" href="#enrolment">{t.askSchedule}<Icon name="arrow" size={17}/></a></div>}</div></section>

    <section id="news" className="section news-section" style={sectionStyle("news")} ><div className="container"><header className="section-heading split"><div><span className="section-kicker"><span/>{sectionValue("news","eyebrow",t.newsKicker)}</span><h2>{sectionValue("news","heading",t.newsTitle)}</h2></div><a className="text-link" href={initialContent.settings.facebook} target="_blank" rel="noreferrer">{t.readOnFacebook}<Icon name="arrow" size={16}/></a></header><div className="news-grid">{initialContent.announcements.slice(0,4).map((item,index)=><article key={item.id} className={index===0?"news-card featured-news":"news-card"}><div className="news-date"><span>{new Intl.DateTimeFormat(lang==="en"?"en-GB":lang==="ps"?"ps-AF":"fa-AF",{day:"2-digit",timeZone:"UTC"}).format(new Date(item.publishedAt))}</span><small>{new Intl.DateTimeFormat(lang==="en"?"en-GB":lang==="ps"?"ps-AF":"fa-AF",{month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(item.publishedAt))}</small></div><div><span className="news-label">{t.update}</span><h3>{localAnnouncement(item,"title",lang)}</h3><p>{localAnnouncement(item,"excerpt",lang)}</p></div></article>)}</div></div></section>

    <section id="faq" className="section faq-section" style={sectionStyle("faq")} ><div className="container faq-layout"><div className="faq-copy"><span className="section-kicker"><span/>{sectionValue("faq","eyebrow",t.faqKicker)}</span><h2>{sectionValue("faq","heading",t.faqTitle)}</h2><p>{sectionValue("faq","body",t.faqBody)}</p><a className="outline-button" href={`tel:${initialContent.settings.phone.replace(/\s/g,"")}`}><Icon name="phone" size={17}/>{t.callNow}</a></div><div className="faq-list">{initialContent.faqs.map(item=><article key={item.id} className={openFaq===item.id?"faq-item open":"faq-item"}><button type="button" onClick={()=>setOpenFaq(openFaq===item.id?null:item.id)} aria-expanded={openFaq===item.id}><span>{localFaq(item,"question",lang)}</span><b>{openFaq===item.id?"−":"+"}</b></button>{openFaq===item.id?<p>{localFaq(item,"answer",lang)}</p>:null}</article>)}</div></div></section>

    <section id="enrolment" className="section enrol-section" style={sectionStyle("enrolment")} ><div className="container enrol-card"><aside className="enrol-aside"><img className="enrol-logo" src="/images/raufi-logo.webp" alt={t.officialLogo}/><span className="section-kicker light"><span/>{sectionValue("enrolment","eyebrow",t.formKicker)}</span><h2>{sectionValue("enrolment","heading",t.formTitle)}</h2><p>{sectionValue("enrolment","body",t.formBody)}</p><div className="contact-stack"><a href={`tel:${initialContent.settings.phone.replace(/\s/g,"")}`}><span><Icon name="phone"/></span><div><small>{t.callNow}</small><strong dir="ltr">{initialContent.settings.phone}</strong></div></a><div><span><Icon name="pin"/></span><div><small>{t.visit}</small><strong>{setting("address")}</strong></div></div></div></aside><div className="enrol-form-wrap"><form onSubmit={submit} className="enrol-form"><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><label>{t.name}<input required minLength={2} maxLength={80} name="name" autoComplete="name"/></label><label>{t.phone}<input required minLength={7} maxLength={30} name="phone" dir="ltr" autoComplete="tel" inputMode="tel"/></label><label>{t.interest}<select required name="interest" value={selectedInterest} onChange={event=>setSelectedInterest(event.target.value)}><option value="" disabled>{t.select}</option>{initialContent.courses.map(course=><option key={course.id} value={course.titleEn}>{localCourse(course,"title",lang)}</option>)}</select></label><label>{t.education}<select name="educationLevel" defaultValue=""><option value="">{t.select}</option>{t.educationOptions.map(option=><option key={option}>{option}</option>)}</select></label><label>{t.preferred}<select name="preferredTime" defaultValue=""><option value="">{t.select}</option>{t.timeOptions.map(option=><option key={option}>{option}</option>)}</select></label><label className="full-field">{t.message}<textarea name="message" maxLength={1000} rows={4}/></label><label className="consent-field"><input type="checkbox" name="consent" required/><span>{t.consent}</span></label><button disabled={formState==="sending"} className="primary-button form-submit" type="submit">{formState==="sending"?t.sending:t.send}<Icon name="arrow" size={17}/></button>{formState==="sent"?<p className="form-alert success"><Icon name="check" size={18}/>{t.sent}</p>:null}{formState==="error"?<p className="form-alert error">{t.failed}</p>:null}</form></div></div></section>

    {customSections.map(section=><BuilderSection key={section.id} section={section} lang={lang} home/>)}
    </div>

    <footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><Brand light large/><p>{t.footerBody}</p><div className="social-links">{[["Instagram",initialContent.settings.instagram],["Facebook",initialContent.settings.facebook],["Telegram",initialContent.settings.telegram]].map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer">{label}</a>)}</div></div><div><h3>{t.quickLinks}</h3><nav>{navigation.slice(0,7).map(item=><a key={item.id} href={item.href}>{item.label}</a>)}</nav></div><div><h3>{t.contactTitle}</h3><p dir="ltr">{initialContent.settings.phone}</p><p>{setting("address")}</p><a href="#enrolment">{t.consult}<Icon name="arrow" size={15}/></a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Raufi Learning Center. {t.rights}</span><Link href="/admin">CMS</Link></div></footer>

    <div className="floating-actions"><a href={`tel:${initialContent.settings.phone.replace(/\s/g,"")}`} aria-label={t.callNow}><Icon name="phone"/></a><a href="#enrolment"><Icon name="message"/><span>{t.consult}</span></a></div>
    {compareIds.length?<div className="compare-tray"><div><span><Icon name="compare"/></span><p><strong>{compareIds.length}/3</strong>{t.compareTitle}</p></div><div className="compare-avatars">{comparedCourses.map(course=><button type="button" key={course.id} title={t.remove} onClick={()=>toggleCompare(course.id)}>{localCourse(course,"title",lang).slice(0,1)}</button>)}</div><button type="button" className="compare-launch" disabled={compareIds.length<2} onClick={()=>setCompareOpen(true)}>{t.compareNow}</button><button type="button" className="compare-clear" onClick={()=>setCompareIds([])}>{t.clear}</button></div>:null}

    {activeCourse?<div className="course-modal-backdrop" role="dialog" aria-modal="true" onMouseDown={event=>{if(event.target===event.currentTarget)setActiveCourse(null);}}><article className="course-modal" dir={dir}><button type="button" className="modal-close" onClick={()=>setActiveCourse(null)} aria-label={t.close}><Icon name="close"/></button><div className="modal-accent" style={{background:activeCourse.accent||"#1261a0"}}/><div className="modal-head"><span className="program-icon" style={{color:activeCourse.accent||"#1261a0",background:`${activeCourse.accent||"#1261a0"}16`}}><Icon name={activeCourse.icon} size={27}/></span><div><small>{localCourse(activeCourse,"category",lang)}</small><h2>{localCourse(activeCourse,"title",lang)}</h2></div></div><p className="modal-description">{localCourse(activeCourse,"description",lang)}</p><div className="modal-details"><div><Icon name="clock"/><span><small>{t.duration}</small><strong>{localCourse(activeCourse,"duration",lang)||"—"}</strong></span></div><div><Icon name="users"/><span><small>{t.level}</small><strong>{localCourse(activeCourse,"level",lang)||"—"}</strong></span></div><div><Icon name="book"/><span><small>{t.format}</small><strong>{localCourse(activeCourse,"format",lang)||"—"}</strong></span></div></div>{localCourse(activeCourse,"outcomes",lang)?<div className="outcomes-list"><h3>{t.outcomes}</h3><ul>{localCourse(activeCourse,"outcomes",lang).split("|").filter(Boolean).map(item=><li key={item}><Icon name="check" size={17}/><span>{item}</span></li>)}</ul></div>:null}<button type="button" className="primary-button modal-cta" onClick={()=>chooseProgramme(activeCourse)}>{t.enrolThis}<Icon name="arrow" size={17}/></button></article></div>:null}

    {compareOpen?<div className="course-modal-backdrop" role="dialog" aria-modal="true" onMouseDown={event=>{if(event.target===event.currentTarget)setCompareOpen(false);}}><article className="compare-modal" dir={dir}><button type="button" className="modal-close" onClick={()=>setCompareOpen(false)} aria-label={t.close}><Icon name="close"/></button><header><span className="section-kicker"><span/>{t.compare}</span><h2>{t.compareTitle}</h2><p>{t.compareBody}</p></header><div className="compare-grid">{comparedCourses.map(course=><article key={course.id} style={{"--course-accent":course.accent} as CSSProperties}><span className="program-icon"><Icon name={course.icon}/></span><h3>{localCourse(course,"title",lang)}</h3><dl><div><dt>{t.duration}</dt><dd>{localCourse(course,"duration",lang)||"—"}</dd></div><div><dt>{t.level}</dt><dd>{localCourse(course,"level",lang)||"—"}</dd></div><div><dt>{t.format}</dt><dd>{localCourse(course,"format",lang)||"—"}</dd></div></dl><button type="button" onClick={()=>chooseProgramme(course)}>{t.enrolThis}<Icon name="arrow" size={15}/></button></article>)}</div></article></div>:null}
  </main>;
}
