import { boolean, integer, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const courses = pgTable("courses", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  titleFa: text("title_fa").notNull(),
  titleEn: text("title_en").notNull(),
  titlePs: text("title_ps").notNull().default(""),
  descriptionFa: text("description_fa").notNull(),
  descriptionEn: text("description_en").notNull(),
  descriptionPs: text("description_ps").notNull().default(""),
  categoryFa: text("category_fa").notNull(),
  categoryEn: text("category_en").notNull(),
  categoryPs: text("category_ps").notNull().default(""),
  durationFa: text("duration_fa").notNull().default(""),
  durationEn: text("duration_en").notNull().default(""),
  durationPs: text("duration_ps").notNull().default(""),
  levelFa: text("level_fa").notNull().default(""),
  levelEn: text("level_en").notNull().default(""),
  levelPs: text("level_ps").notNull().default(""),
  formatFa: text("format_fa").notNull().default(""),
  formatEn: text("format_en").notNull().default(""),
  formatPs: text("format_ps").notNull().default(""),
  outcomesFa: text("outcomes_fa").notNull().default(""),
  outcomesEn: text("outcomes_en").notNull().default(""),
  outcomesPs: text("outcomes_ps").notNull().default(""),
  icon: text("icon").notNull().default("book"),
  accent: text("accent").notNull().default("#1261a0"),
  featured: boolean("featured").notNull().default(false),
  published: boolean("published").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const announcements = pgTable("announcements", {
  id: text("id").primaryKey(),
  titleFa: text("title_fa").notNull(),
  titleEn: text("title_en").notNull(),
  titlePs: text("title_ps").notNull().default(""),
  excerptFa: text("excerpt_fa").notNull(),
  excerptEn: text("excerpt_en").notNull(),
  excerptPs: text("excerpt_ps").notNull().default(""),
  published: boolean("published").notNull().default(true),
  publishedAt: timestamp("published_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const inquiries = pgTable("inquiries", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  phone: text("phone").notNull(),
  interest: text("interest").notNull(),
  educationLevel: text("education_level").notNull().default(""),
  preferredTime: text("preferred_time").notNull().default(""),
  message: text("message").notNull().default(""),
  sourceLanguage: text("source_language").notNull().default("fa"),
  consentAt: text("consent_at").notNull().default(""),
  adminNote: text("admin_note").notNull().default(""),
  status: text("status").notNull().default("new"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const classSchedules = pgTable("class_schedules", {
  id: text("id").primaryKey(),
  courseTitleFa: text("course_title_fa").notNull(),
  courseTitleEn: text("course_title_en").notNull(),
  courseTitlePs: text("course_title_ps").notNull().default(""),
  daysFa: text("days_fa").notNull(),
  daysEn: text("days_en").notNull(),
  daysPs: text("days_ps").notNull().default(""),
  time: text("time").notNull(),
  startDate: text("start_date").notNull().default(""),
  seatsFa: text("seats_fa").notNull().default(""),
  seatsEn: text("seats_en").notNull().default(""),
  seatsPs: text("seats_ps").notNull().default(""),
  published: boolean("published").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const faqs = pgTable("faqs", {
  id: text("id").primaryKey(),
  questionFa: text("question_fa").notNull(),
  questionEn: text("question_en").notNull(),
  questionPs: text("question_ps").notNull().default(""),
  answerFa: text("answer_fa").notNull(),
  answerEn: text("answer_en").notNull(),
  answerPs: text("answer_ps").notNull().default(""),
  published: boolean("published").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const siteSettings = pgTable("site_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const auditLogs = pgTable("audit_logs", {
  id: text("id").primaryKey(),
  action: text("action").notNull(),
  entity: text("entity").notNull(),
  entityId: text("entity_id").notNull().default(""),
  summary: text("summary").notNull().default(""),
  actorEmail: text("actor_email").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const sitePages = pgTable("site_pages", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  titleFa: text("title_fa").notNull(),
  titleEn: text("title_en").notNull(),
  titlePs: text("title_ps").notNull(),
  descriptionFa: text("description_fa").notNull().default(""),
  descriptionEn: text("description_en").notNull().default(""),
  descriptionPs: text("description_ps").notNull().default(""),
  navLabelFa: text("nav_label_fa").notNull().default(""),
  navLabelEn: text("nav_label_en").notNull().default(""),
  navLabelPs: text("nav_label_ps").notNull().default(""),
  isHome: boolean("is_home").notNull().default(false),
  showInNav: boolean("show_in_nav").notNull().default(true),
  published: boolean("published").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});

export const pageSections = pgTable("page_sections", {
  id: text("id").primaryKey(),
  pageId: text("page_id").notNull(),
  sectionKey: text("section_key").notNull(),
  type: text("type").notNull().default("richText"),
  name: text("name").notNull(),
  eyebrowFa: text("eyebrow_fa").notNull().default(""),
  eyebrowEn: text("eyebrow_en").notNull().default(""),
  eyebrowPs: text("eyebrow_ps").notNull().default(""),
  headingFa: text("heading_fa").notNull().default(""),
  headingEn: text("heading_en").notNull().default(""),
  headingPs: text("heading_ps").notNull().default(""),
  bodyFa: text("body_fa").notNull().default(""),
  bodyEn: text("body_en").notNull().default(""),
  bodyPs: text("body_ps").notNull().default(""),
  imageUrl: text("image_url").notNull().default(""),
  secondaryImageUrl: text("secondary_image_url").notNull().default(""),
  imageAltFa: text("image_alt_fa").notNull().default(""),
  imageAltEn: text("image_alt_en").notNull().default(""),
  imageAltPs: text("image_alt_ps").notNull().default(""),
  ctaLabelFa: text("cta_label_fa").notNull().default(""),
  ctaLabelEn: text("cta_label_en").notNull().default(""),
  ctaLabelPs: text("cta_label_ps").notNull().default(""),
  ctaUrl: text("cta_url").notNull().default(""),
  navLabelFa: text("nav_label_fa").notNull().default(""),
  navLabelEn: text("nav_label_en").notNull().default(""),
  navLabelPs: text("nav_label_ps").notNull().default(""),
  itemsJson: text("items_json").notNull().default("[]"),
  theme: text("theme").notNull().default("light"),
  showInNav: boolean("show_in_nav").notNull().default(false),
  published: boolean("published").notNull().default(true),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
},table=>[uniqueIndex("page_sections_page_key_unique").on(table.pageId,table.sectionKey)]);

export const mediaAssets = pgTable("media_assets", {
  id: text("id").primaryKey(),
  objectKey: text("object_key").notNull().unique(),
  filename: text("filename").notNull(),
  contentType: text("content_type").notNull(),
  size: integer("size").notNull(),
  altFa: text("alt_fa").notNull().default(""),
  altEn: text("alt_en").notNull().default(""),
  altPs: text("alt_ps").notNull().default(""),
  uploadedBy: text("uploaded_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(),
});
